### ISSUE TITLE
How to train the network

### ISSUE THREAD

**Issue by fukexue** [yewzijian/3DFeatNet#1]
Hello, I'm sorry to interrupt. Is it convenient to provide a training version of the code?

**Comment by yewzijian** [comment]
Hi, the training code is available in the repository. We provide a bash script train.sh to perform the training on our data, which internally calls train.py. Please see the main README.md for details.

**Comment by fukexue** [comment]
Thank you for your reply.

**Comment by fukexue** [comment]
Sorry to bother you, I only generated train folder and train. TXT using two script files of your pre-processing Oxford dataset, but train. py needs cluster folder. How does cluster folder generate?

**Comment by fukexue** [comment]
Tips for errors as shown in the figure during training.
![2019-01-20 13-31-42](https://user-images.githubusercontent.com/25931191/51435673-c454de80-1cb7-11e9-81d7-f570217f7b1f.png)

**Comment by yewzijian** [comment]
Hi @fukexue, the cluster folder is the test data used to used to generate Table 2 in our paper. See the README.md in the scripts_data_processing folder for the download link. You will likely get _better_ results than the values reported in our paper as we've tweaked the training protocol slightly.

Alternatively you can just comment out the parts which use these clusters; they do not affect the training in any way.
