### ISSUE TITLE
About the "keypoints -> clusters" procession during training

### ISSUE THREAD

**Issue by hxwork** [yewzijian/3DFeatNet#14]
Hi,
    Thank you for your open source codes first, and when I read your codes, I found that the "keypoints -> clusters" procession is repeated twice in feature detection and feature extraction module. Why can not just take the "cluster" from feature detection module as the input of feature extraction module directly ?

**Comment by yewzijian** [comment]
Yes that can certainly be done. I left it separate to allow for different parameters (e.g. cluster radius) to be used for feature detection and extraction, although I eventually ended up using the same radius.

**Comment by hxwork** [comment]
Thank you for your reply ! I have deleted the "keypoints -> clusters" procession in feature extraction module, but it seems that the convergence speed of FP rate is slower than before, maybe I have written a bug, I will check the codes again.
