### ISSUE TITLE
error occured during training with TF 1.15.0

### ISSUE THREAD

**Issue by hxwork** [yewzijian/3DFeatNet#15]
Hi,
    I tried to train with TF 1.14, but it can't work successfully, a "Segmentation Fault" has been reported. And then I tried to use TF 1.15, but it still can't train the network, the error is as following:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' used by node detection/FarthestPointSample (defined at /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [npoint=512]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'
`
    It seems FPS procession can't work fine, but I can't fix it. I saw your reply in another issue that you can successfully train with TF 1.15, my environment is as following:
python==3.5
TF==1.15.0
cuda==10.0
cudnn==7.6.0

**Comment by yewzijian** [comment]
My setting with TF1.15 was with cudnn 7.4.2.

While my inference code works on TF1.15, I never tried training on it before. I recommend using a older tensorflow version, since the code was developed quite a long time ago under TF1.4.

**Comment by hxwork** [comment]
Thank you a lot ! I just want to use tensorboard 3D for show during training, so that's why I want to use TF >= 1.14, I will try to deal with that. Thank you again for your reply !
