### ISSUE TITLE
can you provide you model which you have trained?

### ISSUE THREAD

**Issue by MrCrazyCrab** [yewzijian/3DFeatNet#17]
can you provide you model which you have trained, is there any possible to register two point clouds which have differet size and have some part can be overlapped?

**Comment by yewzijian** [comment]
The model is available from [here](https://drive.google.com/open?id=1JYZvFmMO3hgLN4ao3MqcMVgHYZtHhPOv).
This is a feature based method, so it works on point clouds of different sizes and extent.

**Comment by MrCrazyCrab** [comment]
@yewzijian Thanks, i would try it later.
