### ISSUE TITLE
question about the NMS module？

### ISSUE THREAD

**Issue by MrCrazyCrab** [yewzijian/3DFeatNet#18]
I have test the model you have sent to me, and there is some confuse in the inference code about the NMS module. Why did you need the NMS to process the data, what's the difference between the attention and feature in the  code. I found the output is not the same size as the input through NMS module. i want to do a visualization of the whole point cloud after registeration not some of it. Can you solve my problem. Wish for you reply.
Thanks!

**Comment by yewzijian** [comment]
Attention indicates how useful each point is for registration problem. We use the attention to pick out the more salient points in the point cloud, and use the feature descriptors for those salient points for matching. This improves efficiency and possibly robustness, as the less descriptive points are ignored. Do refer to our paper for more details.

**Comment by MrCrazyCrab** [comment]
@yewzijian Thanks, and I have reread you paper again. Now, i want to retrain the model with my data, i am not sure the function of `    def load_metadata(self, path):
        self.paths_and_labels = []
        with open(path) as f:
            for line in f:
                fname, positives, negatives = [l.strip() for l in line.split('|')]
                positives = [int(s) for s in positives.split()]
                nonnegatives = [int(s) for s in negatives.split()]

                self.paths_and_labels.append((fname, set(positives), set(nonnegatives)))`
I can't understand the original data you have used. Can you explain clearly about it?

**Comment by yewzijian** [comment]
For efficiency, the positives and negatives are precomputed based on their GPS distances. So `fname` contains the path to the anchor point cloud, and `positives` and `negatives` contains the positive and negative point clouds respectively.

The dataset [readme](https://github.com/yewzijian/3DFeatNet/blob/master/scripts_data_processing/Readme.md#training-data) describes the dataset format, might be useful to take a look.

**Comment by MrCrazyCrab** [comment]
@yewzijian There is a little problem in my dataset, i did't have the GPS distance, just the point could with xysNxNyNz. So how can i to calculate the positive and the negatives for my own data training?

**Comment by yewzijian** [comment]
This work is a weakly-supervised work, it makes use of the GPS to know which point clouds overlap with each other.
If you don't have the approximate/accurate pose of the point clouds it is a much harder problem to learn.
