### ISSUE TITLE
How to convert point clouds in other formats

### ISSUE THREAD

**Issue by maradanovic** [yewzijian/3DFeatNet#20]
Hi,

Thanks for sharing your code, awesome work.

Just a short question - what software/method do you use to convert point clouds from different formats into the no-header, Nx6x4 bytes .bin file (as per [this ](https://github.com/yewzijian/3DFeatNet/issues/9) thread)?

Thanks a lot!

**Comment by yewzijian** [comment]
Hi, I generated the files using my own Python script. You might find Numpy's [tofile](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tofile.html) method useful.


Zi Jian

**Comment by maradanovic** [comment]
Thanks a lot Zi Jian, I wrote my own script - the hint was golden
