### ISSUE TITLE
Trained models used in the paper

### ISSUE THREAD

**Issue by fdila** [yewzijian/3DFeatNet#21]
Hi, i noticed that the pretrained model you made available outputs a vector with 32 features, while the registration tests shown in the supplementary material used feature vectors with higher dimensionality.
Did you notice any differences in performances using a higher dimensionality? In that case, could you make those pretrained models available? 
Thank you

**Comment by yewzijian** [comment]
Hi, the registration results are all based on 32D features. We did experiment with larger number of dimensions but that yielded diminishing improvements (see Fig. 3 in main paper for feature matching performance). The supplementary material are also based on the same 32D feature descriptors.

Unfortunately, I no longer have the checkpoints for the other dimensionalities.

**Comment by fdila** [comment]
Thanks
