### ISSUE TITLE
how to use trained model on my data with format .ply or .pcd?

### ISSUE THREAD

**Issue by ltj95** [yewzijian/3DFeatNet#9]
Hello! I want to use cloudcompare to convert my data for the format .bin,but   when I run inference.py on my data with format .bin, error occur like 

![微信图片_20190701104412](https://user-images.githubusercontent.com/32707854/60407420-49d8a500-9bed-11e9-9805-ecc8e5bd94c7.png)

How to sovle the problem?

**Comment by yewzijian** [comment]
Hi, if you get this error it means that the input file is not in the expected format. I'm not sure what cloudcompare saves to, but my code assumes the point cloud is stored as Nx6 float32's, with each row containing x,y,z,nx,ny,nz (the nx, ny, nz are normals which are unused in this code).
For other formats, it should be easy to modify the load_point_cloud function to your needs.

**Comment by ltj95** [comment]
I convert a pointcloud with  Nx6 float32's  to .bin file,it's the same error.
I also use .txt file ,it has no result.My raw pointcloud data content like this 
![微信图片_20190701135019](https://user-images.githubusercontent.com/32707854/60413341-30dced80-9c07-11e9-8c36-90b90177044c.png)

**Comment by yewzijian** [comment]
Check if the file size of your .bin file is exactly Nx6x4 bytes for a point cloud of N points?
